name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: simple

      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/L1ghtmann/theos/swift-tc/bin/install-theos)"

      - name: Build
        run: |
          cd simple
          make package THEOS_PACKAGE_SCHEME=rootless

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: simple/packages/null.leptos.simple_0.0.1-1+debug_iphoneos-arm64.deb
          if-no-files-found: error
